# -*- coding: utf-8 -*-
"""mental_health_disorder_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5SupBzNE5jY1WMVsqiSjTIbm9limFyx
"""

pip install transformers torch scikit-learn pandas numpy

import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments
)

df = pd.read_csv("/dataset.csv")

# Drop nulls
df.dropna(subset=['text', 'title', 'target'], inplace=True)

# Combine title + text
df['combined_text'] = df['title'] + " " + df['text']

# Labels
df['target'] = df['target'].astype(int)

train_texts, test_texts, train_labels, test_labels = train_test_split(
    df['combined_text'].tolist(),
    df['target'].tolist(),
    test_size=0.2,
    random_state=42,
    stratify=df['target']
)

tokenizer = DistilBertTokenizerFast.from_pretrained(
    "distilbert-base-uncased"
)

train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=256
)

test_encodings = tokenizer(
    test_texts,
    truncation=True,
    padding=True,
    max_length=256
)

class MentalHealthDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx])
                for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = MentalHealthDataset(train_encodings, train_labels)
test_dataset = MentalHealthDataset(test_encodings, test_labels)

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(set(train_labels))
)

pip install -U transformers

import transformers
print(transformers.__version__)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",        # ✅ renamed
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=4,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    logging_dir="./logs",
    logging_steps=100
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, predictions)
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
    tokenizer=tokenizer
)

trainer.train()

predictions = trainer.predict(test_dataset)
y_pred = np.argmax(predictions.predictions, axis=1)

print("Accuracy:", accuracy_score(test_labels, y_pred))
print("\nClassification Report:\n")
print(classification_report(test_labels, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(test_labels, y_pred))

trainer.save_model("./final_model")
tokenizer.save_pretrained("./final_model")

from google.colab import files
!zip -r final_model.zip final_model
files.download("final_model.zip")

import pandas as pd
df = pd.read_csv('/dataset.csv')  # Adjust filename if needed
df.dropna(subset=['text', 'title', 'target'], inplace=True)
df['combined_text'] = df['title'] + " " + df['text']
df['target'] = df['target'].astype(int)
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

train_texts, test_texts, train_labels, test_labels = train_test_split(
    df['combined_text'], df['target'], test_size=0.2, random_state=42, stratify=df['target']
)

vectorizer = TfidfVectorizer(max_features=5000)
X_train = vectorizer.fit_transform(train_texts)
X_test = vectorizer.transform(test_texts)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, train_labels)
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(test_labels, y_pred))
print(classification_report(test_labels, y_pred))
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load and prepare dataset
df = pd.read_csv("/dataset.csv")
df.dropna(subset=["text", "title", "target"], inplace=True)
df["combined_text"] = df["title"] + " " + df["text"]
df["target"] = df["target"].astype(int)

# Train-test split
train_texts, test_texts, train_labels, test_labels = train_test_split(
    df["combined_text"].tolist(),
    df["target"].tolist(),
    test_size=0.2,
    random_state=42,
    stratify=df["target"],
)

# TF-IDF vectorization
vectorizer = TfidfVectorizer(max_features=5000)
X_train = vectorizer.fit_transform(train_texts)
y_train = train_labels
X_test = vectorizer.transform(test_texts)

# SVM model
svm_model = svm.SVC(kernel="linear", C=1)

# Train model
svm_model.fit(X_train, y_train)

# Predict
y_pred = svm_model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(test_labels, y_pred))
print("\nClassification Report:\n")
print(classification_report(test_labels, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(test_labels, y_pred))

y_pred_lr = model.predict(X_test)
lr_accuracy = accuracy_score(test_labels, y_pred_lr)

y_pred_svm = svm_model.predict(X_test)
svm_accuracy = accuracy_score(test_labels, y_pred_svm)

bert_accuracy = accuracy_score(test_labels, y_pred)

results_df = pd.DataFrame({
    "Model": [
        "Logistic Regression (TF-IDF)",
        "SVM (TF-IDF)",
        "DistilBERT (Proposed)"
    ],
    "Accuracy (%)": [
        round(lr_accuracy * 100, 2),
        round(svm_accuracy * 100, 2),
        round(bert_accuracy * 100, 2)
    ]
})

print(results_df)

import pandas as pd

# Final test results (from your outputs)
results_data = {
    "Model": [
        "Logistic Regression (TF-IDF)",
        "SVM (TF-IDF)",
        "DistilBERT (Proposed)"
    ],
    "Accuracy": [0.7941, 0.7950, 0.8306],
    "Precision": [0.80, 0.80, 0.83],
    "Recall": [0.79, 0.80, 0.83],
    "F1-Score": [0.80, 0.80, 0.83]
}

results_df = pd.DataFrame(results_data)

# Convert to percentage (optional, but looks nicer)
results_df[["Accuracy", "Precision", "Recall", "F1-Score"]] = \
    results_df[["Accuracy", "Precision", "Recall", "F1-Score"]] * 100

results_df = results_df.round(2)

print(results_df)

results_df.to_csv("results_comparison_table.csv", index=False)

